### ISSUE TITLE
Suggest a multimodal dataset

### ISSUE THREAD

**Issue by matrix-alpha** [Yutong-Zhou-cv/Awesome-Text-to-Image#15]
Thanks for the curated list of multimodal LLM. We have a related work that we hope is added to this awesome repository.

Accountable Textual-Visual Chat Learns to Reject Human Instructions in Image Re-creation (https://arxiv.org/pdf/2303.05983.pdf)

Project Page: https://matrix-alpha.github.io/

**Comment by Yutong-Zhou-cv** [comment]
@matrix-alpha Thank you for sharing:)
Your excellent work has been added to both of my two repos ([Awesome-Text-to-Image](https://github.com/Yutong-Zhou-cv/awesome-Text-to-Image) and [Awesome-Multimodality
](https://github.com/Yutong-Zhou-cv/Awesome-Multimodality)).
