### ISSUE TITLE
Survey Text Based Image Synthesis Methods

### ISSUE THREAD

**Issue by prajwalsingh** [Yutong-Zhou-cv/Awesome-Text-to-Image#5]
I am currently surveying text-based image synthesis methods and compiling them in the form of a blog. Here is the link [https://hackmd.io/@prajwalsingh/imagesynthesis]. I hope this might help others. (open for collaboration)

**Comment by Yutong-Zhou-cv** [comment]
@prajwalsingh I have added your excellent survey blog to this repo. Thank you for your valuable contribution.

**Comment by prajwalsingh** [comment]
Thank you :)
