### ISSUE TITLE
An new version of FID and IS evaluation code

### ISSUE THREAD

**Issue by senmaoy** [Yutong-Zhou-cv/Awesome-Text-to-Image#7]
I provided a new version of FID and IS evaluation code at https://github.com/senmaoy/Inception-Score-FID-on-CUB-and-OXford.git
It's better to update it as some people report that they failed to run the original TensorFlow code. And it's really troublesome to install old version tensorflows

**Comment by Yutong-Zhou-cv** [comment]
Hi,senmaoy. Thank you so much for your generous contribution to the new version of IS and FID. 
I have added your nice evaluation code to this repo and believe that it will be helpful for future research.
Have a nice day.
