### ISSUE TITLE
GLIDE has been accepted by ICML 2022

### ISSUE THREAD

**Issue by qiaojy19** [Yutong-Zhou-cv/Awesome-Text-to-Image#9]
[ICML 2022 link](https://icml.cc/Conferences/2022/AcceptedPapersInitial)

![image](https://user-images.githubusercontent.com/11640301/173124964-cebe8438-8866-4bec-acaa-f3c63413eaeb.png)

**Comment by Yutong-Zhou-cv** [comment]
Hi, @qiaojy19 .Thanks for your mention! I have updated the GLIDE tag.
